# Numpy Arrays

In [2]:
import numpy as np


In [7]:
ml = [1,2,2]

In [8]:
ml1 = np.array(ml)
ml1

array([1, 2, 2])

In [11]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [12]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.42077527, 0.77745453, 0.27787953, 0.80761554, 0.80294911])

In [21]:
np.random.rand(3,3)

array([[0.40687264, 0.38126659, 0.69407093],
       [0.06723995, 0.00519165, 0.80666819],
       [0.39082173, 0.70324164, 0.43659764]])

In [22]:
np.random.randn(2)

array([1.55200716, 0.2054415 ])

In [23]:
np.random.randn(2,3)

array([[ 0.28570266,  0.58412977, -0.11375146],
       [-0.50513295, -1.36837792, -0.10215285]])

In [25]:
np.random.randint(1,100,10)

array([52, 73, 25, 12, 52,  8,  3, 52,  4, 15])

In [27]:
a1 = np.arange(25)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
a2 = np.random.randint(0,50,10)
a2

array([ 5,  7,  4, 23, 15, 38, 26, 33, 43,  4])

In [30]:
a1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
a1.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [33]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
a1.max()

24

In [39]:
a2 =np.random.randint(0,15,10)
a2

array([14, 11,  6,  3,  5, 11, 13,  7, 13,  7])

In [40]:
a2.max()

14

In [41]:
a2.argmax()

0

In [42]:
a2.min()


3

In [43]:
a2.argmin()

3

In [44]:
a2.shape

(10,)

In [47]:
a22 = a2.reshape(2,5)
a22

array([[14, 11,  6,  3,  5],
       [11, 13,  7, 13,  7]])

In [48]:
a22.shape

(2, 5)

In [50]:
a22.dtype

dtype('int32')